ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "utmSource" TEXT;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "utmMedium" TEXT;
ALTER TABLE "PageView" ADD COLUMN IF NOT EXISTS "utmCampaign" TEXT;
