ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "gtin" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "mpn" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "condition" TEXT NOT NULL DEFAULT 'new';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "googleProductCategory" TEXT;
